-- Add semantic_blocks column to campaigns table
-- This stores the AI-generated semantic blocks (hero, features, cta, etc.)
-- which can be lazily converted to EmailComponent tree when editor opens

ALTER TABLE campaigns
ADD COLUMN IF NOT EXISTS semantic_blocks JSONB;

-- Add comment for documentation
COMMENT ON COLUMN campaigns.semantic_blocks IS 'V2: Semantic content blocks generated by AI (hero, features, cta, footer, etc.)';

-- Note: root_component will be NULL on initial generation and populated lazily when editor opens

